all: unicast_project
PROJECT_SOURCEFILES += distance.c
PROJECT_SOURCEFILES += settings.c
PROJECT_SOURCEFILES += sink.c
PROJECT_SOURCEFILES += moron.c
CONTIKI = ../../contiki
CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
